"""Generate a service stub from a .proto file."""

import os
import re
from pathlib import Path
from typing import List, Optional

from ..message_factory import MessageFactory
from .config import CliConfig, load_config, resolve_path


class InvalidServiceNameError(Exception):
    """A service name that could not be used safely in a file path."""

    def __init__(self, name: str, reason: str) -> None:
        super().__init__(f"invalid service name {name!r}: {reason}")


_SAFE_NAME = re.compile(r"^[A-Za-z0-9_-]+$")


def assert_safe_service_name(name: str) -> str:
    """
    Validate a service name before it is interpolated into a filesystem path.

    The name arrives from argv and is joined onto the configured proto and
    services directories, so anything containing a separator or a ``..``
    segment writes outside them. Rather than sanitising — which invites
    disagreement between what was asked for and what was written — reject
    and say why. Returns the name unchanged.
    """
    if not isinstance(name, str) or not name:
        raise InvalidServiceNameError(str(name), "must be a non-empty string")
    if len(name) > 100:
        raise InvalidServiceNameError(name, "must be 100 characters or fewer")
    if not _SAFE_NAME.match(name):
        raise InvalidServiceNameError(name, "may contain only letters, digits, underscore and hyphen")
    return name


def to_snake_case(name: str) -> str:
    s1 = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s1).lower()


# 1.x private name, kept for callers that imported it.
_to_snake_case = to_snake_case


def generate_service(
    service_name: str,
    config: Optional[CliConfig] = None,
    output_dir: Optional[str] = None,
    cwd: Optional[str] = None,
) -> str:
    """
    Generate a stub for ``<service_name>.proto``: a RunnableService with one
    ``async def`` per rpc (an async generator for a server-streaming one),
    taken from the parsed schema rather than a regex over the text.
    Returns the path written. Raises rather than exiting, so it can be
    called from a script or a test.
    """
    assert_safe_service_name(service_name)
    cwd = cwd or os.getcwd()
    cfg = config or load_config(cwd)
    proto_dir = resolve_path(cfg.proto_dir, cwd)
    services_dir = resolve_path(output_dir or cfg.services_dir, cwd)

    proto_file = os.path.join(proto_dir, f"{service_name}.proto")
    if not os.path.exists(proto_file):
        raise FileNotFoundError(f"Proto file not found: {proto_file}")

    factory = MessageFactory()
    factory.init([])
    with open(proto_file, "r", encoding="utf-8") as fh:
        factory.parse(fh.read(), service_name)
    assert factory.root is not None

    fdp = next(iter(f for name, f in factory.root.files.items() if name.startswith("protobus/") and f.service), None)
    if fdp is None or not fdp.service:
        raise ValueError(f"Could not find a service definition in {proto_file}")
    service_proto = fdp.service[0]
    full_service_name = f"{fdp.package}.{service_proto.name}" if fdp.package else service_proto.name
    descriptor = factory.root.lookup_service(full_service_name)

    class_name = f"{service_name}Service"
    methods: List[str] = []
    for method in descriptor.methods:
        req = method.input_type.name
        res = method.output_type.name
        if method.server_streaming:
            methods.append(
                f"    async def {method.name}(self, request: dict, actor: str, correlation_id: str, context: MessageHandlerContext):\n"
                f"        \"\"\"{req} -> stream of {res}. Yield one dict per chunk; watch context.signal to stop early.\"\"\"\n"
                f"        raise NotImplementedError(\"{method.name}\")\n"
                f"        yield {{}}  # pragma: no cover\n"
            )
        else:
            methods.append(
                f"    async def {method.name}(self, request: dict, actor: str, correlation_id: str) -> dict:\n"
                f"        \"\"\"{req} -> {res}.\"\"\"\n"
                f"        raise NotImplementedError(\"{method.name}\")\n"
            )

    code = f'''"""
{full_service_name} implementation.

Generated by protobus CLI. Implement the methods below.
"""

import asyncio
import os

from protobus import Context, MessageHandlerContext, RunnableService


class {class_name}(RunnableService):
    service_name = "{full_service_name}"

{chr(10).join(methods)}

async def main() -> None:
    context = Context()
    await context.init(
        os.environ.get("AMQP_URL", "amqp://guest:guest@localhost:5672/"),
        [os.environ.get("PROTO_PATH", "{cfg.proto_dir}")],
    )
    await {class_name}.start(context)


if __name__ == "__main__":
    asyncio.run(main())
'''

    service_sub_dir = Path(services_dir) / service_name.lower()
    service_sub_dir.mkdir(parents=True, exist_ok=True)
    output_file = service_sub_dir / f"{to_snake_case(service_name)}_service.py"
    # Containment: the validated name cannot escape, but check the resolved
    # path anyway so a misconfigured services_dir cannot either.
    if Path(os.path.commonpath([Path(services_dir).resolve(), output_file.resolve()])) != Path(services_dir).resolve():
        raise InvalidServiceNameError(service_name, "resolved outside the services directory")
    if output_file.exists():
        raise FileExistsError(f"Service file already exists: {output_file}. Remove it first if you want to regenerate.")
    output_file.write_text(code, encoding="utf-8")
    print(f"Service generated: {output_file}")
    return str(output_file)
